pipeline:
  build:
    image: node:16
    commands:
      - npm install
      - npm run build
  tests:
    image: python:3.11.2
    commands:
      - pip install -r requirements.txt
      - python manage.py test --settings=myapp.settings.testing