# Generated by Django 4.2.5 on 2023-10-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_ordenes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenes',
            options={'verbose_name_plural': 'Ordenes'},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name_plural': 'Productos'},
        ),
    ]
